name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: |
        docker build -t lolei-app:ci .

    - name: Run container for testing
      run: |
        docker run -d --name lolei-app-ci -p 5000:5000 lolei-app:ci

        sleep 5

        RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:5000/)
        echo "HTTP response code: $RESPONSE"
        if [ "$RESPONSE" -ne 200 ]; then
        echo "Container test failed"
        exit 1
        fi

    - name: Stop container
      run: |
        docker stop lolei-app-ci
        docker rm lolei-app-ci
